### ISSUE TITLE
Visual studio themes

### ISSUE THREAD

**Issue by eberkund** [rainglow/vs#2]
I came across this project: https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.VisualStudio2017ColorThemeEditor

And it looks like this is the supported way of having themes in Visual Studio.

![image](https://user-images.githubusercontent.com/4555959/34677344-d34b8a98-f45d-11e7-967e-27f1bce5d203.png)

The themes in this repo are in a different format though. I think this is the way to go if the ultimate goal is having a extension you can install with all the themes.

**Comment by rileytb** [comment]
I agree with this, if nothing else because it's more simple. I couldn't find the "My Settings" and had to do another import and have it override my current settings for it to work.

**Comment by daylerees** [comment]
I'm using the Mac version of Visual Studio as my test platform for this, but I'm starting to wonder if they use different theme types. If I get a chance I'll install VS on my Windows computer and have a play around. Sorry about that guys! I'll keep you updated.

**Comment by eberkund** [comment]
As far as I know, Visual Studio for Mac is an entirely different application that is a rebranded Xamarin Studio with very little in common with Visual Studio for Windows.

Fortunately the themes for Visual Studio extension is open source: https://github.com/Microsoft/VS-ColorThemes Maybe we could just copy that and create a new repo so VS for Mac and Windows are separate?

**Comment by daylerees** [comment]
The Windows themes appear to be over 8000 lines long, so I think it might take a little while before those show up I'm afraid guys. 😂 I'll see what I can do, though.

**Comment by daylerees** [comment]
Hey guys, I've added VS support for windows to the project plan https://github.com/orgs/rainglow/projects/1 and I've also added a Mac only notice to the install section of the VS themes project.

Going to close this for now. Thanks for bringing this to my attention!
